name: WheelsAPI-Docker

services:
  database:
    image: postgres:17-bookworm
    container_name: db_postgres
    environment:
      POSTGRES_DB: wheelsDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4845d91eb156d325aa6da14f6
    volumes:
      - postgres_data:/var/lib/postgres/data
    ports:
      - "5433:5432"

  application:
    image: wheelsapi:0.0.1
    container_name: application_wheelsapi
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./entrypoint.sh
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:4845d91eb156d325aa6da14f6@db_postgres:5432/wheelsDB
    restart: on-failure

volumes:
  postgres_data:
