name: WheelsAPI-Docker

services:
  database:
    image: postgres:17
    environment:
      POSTGRES_DB: wheelsDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4845d91eb156d325aa6da14f6
    volumes:
      - database_data: /var/lib/postgres
    ports:
      - 5433:5432

  # application:
  #   depends_on:
  #     - database

volumes:
  database_data:
