"""Update table vehicles with type and plate

Revision ID: 3f1dd0361cc1
Revises: 52c9ea2e8185
Create Date: 2025-04-11 13:33:16.392400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f1dd0361cc1'
down_revision: Union[str, None] = '52c9ea2e8185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    types_vehicle = postgresql.ENUM(
        'car', 'truck', 'bus', 'bike', 'jet_ski',
        name='types_vehicle'
    )
    types_vehicle.create(op.get_bind())

    op.add_column('vehicles', sa.Column('plate', sa.String(), nullable=False))
    op.add_column('vehicles', sa.Column(
        'type',
        postgresql.ENUM(
            'car', 'truck', 'bus', 'bike', 'jet_ski',
            name='types_vehicle'
        ),
        nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'type')
    op.drop_column('vehicles', 'plate')

    types_vehicle = postgresql.ENUM(
        'car', 'truck', 'bus', 'bike', 'jet_ski',
        name='types_vehicle'
    )
    types_vehicle.drop(op.get_bind())
    # ### end Alembic commands ###
