"""Update tables cascade

Revision ID: 8c043918712d
Revises: aaa13ee127ab
Create Date: 2025-04-16 10:02:56.933073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c043918712d'
down_revision: Union[str, None] = 'aaa13ee127ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sales_id_vehicle_fkey', 'sales', type_='foreignkey')
    op.create_foreign_key(None, 'sales', 'vehicles', ['id_vehicle'], ['id'], ondelete='CASCADE')
    op.drop_constraint('vehicles_img_id_vehicle_fkey', 'vehicles_img', type_='foreignkey')
    op.create_foreign_key(None, 'vehicles_img', 'vehicles', ['id_vehicle'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles_img', type_='foreignkey')
    op.create_foreign_key('vehicles_img_id_vehicle_fkey', 'vehicles_img', 'vehicles', ['id_vehicle'], ['id'])
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.create_foreign_key('sales_id_vehicle_fkey', 'sales', 'vehicles', ['id_vehicle'], ['id'])
    # ### end Alembic commands ###
