"""Update table vehicles cascade user_id

Revision ID: aaa13ee127ab
Revises: b8342183aade
Create Date: 2025-04-16 09:58:30.023154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa13ee127ab'
down_revision: Union[str, None] = 'b8342183aade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vehicles_id_user_fkey', 'vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicles', 'users', ['id_user'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.create_foreign_key('vehicles_id_user_fkey', 'vehicles', 'users', ['id_user'], ['id'])
    # ### end Alembic commands ###
