"""Update table vehicles and vehicles_img referring to ID's

Revision ID: b8342183aade
Revises: 8c1198d13774
Create Date: 2025-04-13 11:24:05.125049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8342183aade'
down_revision: Union[str, None] = '8c1198d13774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vehicles_id_img_fkey', 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'id_img')
    op.add_column('vehicles_img', sa.Column('id_vehicle', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'vehicles_img', 'vehicles', ['id_vehicle'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles_img', type_='foreignkey')
    op.drop_column('vehicles_img', 'id_vehicle')
    op.add_column('vehicles', sa.Column('id_img', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('vehicles_id_img_fkey', 'vehicles', 'vehicles_img', ['id_img'], ['id'])
    # ### end Alembic commands ###
